version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/self-jobs-range.yml

env:
  global:
    - REQUIRE_EXTRA="silverstripe-themes/simple:^3"
    - PHPUNIT_SUITE="recipe-collaboration"
